name: flutter_inappwebview_helper
description: "A Flutter package that provides helper functions and classes for working with InAppWebView. for esier get data from webview."
version: 1.0.0
repository: https://github.com/genss333/flutter_inappwebview_helper.git

environment:
  sdk: ^3.5.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_inappwebview: ^5.7.2+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0




