name: flutter_inappwebview_helper
description: "for flutter_inappwebview plugin helper"
version: 0.0.1
homepage: https://flutter.dev

environment:
  sdk: ^3.5.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_inappwebview: ^5.7.2+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.genss333.flutter_inappwebview_helper
        pluginClass: WebViewHelperAndroid
      ios:
        pluginClass: WebViewHelperIos


